Add slider to configure initial food amount
david-d25/cell-sandbox pull request #17
Opened 2022-10-14 17:21 UTC by justkate1905

2022-10-15 00:12 UTC, olegthelilfix approved these changes

2022-10-15 19:52 UTC, david-d25 requested changes

2022-10-15 19:52 UTC, david-d25 commented on src/main/kotlin/com/devexperts/openhack2022/cell_sandbox/gui/WorldSettingsPanel.kt
> +        val initialFoodAmountSlider = Slider(500.0, 1500.0, 1000.0)
I think, in some experiments, there would be preferable to have no food on the stage (i.e. when light & photocytes are used).
What if we set 0.0 as the minimum amount of food here?

2022-10-15 19:57 UTC, vaimer approved these changes

2022-10-15 19:58 UTC, vaimer approved these changes

2022-10-16 11:55 UTC, david-d25 approved these changes

2022-10-16 11:55 UTC, merged