fixed some graphics issues
david-d25/cell-sandbox pull request #31
Opened 2022-10-21 01:08 UTC by david-d25

2022-10-21 01:08 UTC, david-d25 commented
Unfortunately, weren't able to fix *all* issues, but most of them are fixed.

2022-10-22 19:03 UTC, olegthelilfix requested changes

2022-10-22 19:03 UTC, olegthelilfix commented on src/main/kotlin/com/devexperts/openhack2022/cell_sandbox/game/renderer/CellRenderer.kt
> +            if (intersection != null) {
it would be better to put this 3 if's to one

2022-10-22 19:03 UTC, olegthelilfix commented on src/main/kotlin/com/devexperts/openhack2022/cell_sandbox/game/renderer/CellRenderer.kt
>          context.save()
Function render look really giant, so can we try to split it?

2022-10-23 00:01 UTC, olegthelilfix approved these changes

2022-10-23 00:04 UTC, merged